<?php

/**
 * @file
 * Install, update and uninstall functions for the zap_initialize module.
 */

use Drupal\user\Entity\User;
use Drupal\user\RoleInterface;

/**
 * Implements hook_install().
 */
function zap_initialize_install() {
  \Drupal::configFactory()->getEditable('system.site')->set('name', 'Office of Information Technology')->save(TRUE);
  \Drupal::configFactory()->getEditable('system.site')->set('mail', 'help@colorado.edu')->save(TRUE);
}
